version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/packages/markitdown"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/packages/markitdown-mcp"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/packages/markitdown-sample-plugin"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
